name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET
      run : echo setup before
   #   uses: actions/setput-dotnet@v3
   #   with:
  #      dotnet-version: 8.0.x
  #  - name: Install MAUI Workload
  #    run: dotnet workload install maui

    - name: Restore Dependency
      run: dotnet restore
      working-directory: ./MauiDeploy
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

