name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET
      uses: actions/setput-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore
      working-directory: ./MauiDeploy

    - name: Build
      run: dotnet build -c Release -f:net8.0-windows10.0.19041.0
      working-directory: ./MauiDeploy
